### ISSUE TITLE
Creating a Contract Bug

### ISSUE THREAD

**Issue by RichardGOV** [BVCOG-Contract-Management/BVGOG-Contract-Manager#72]
Howdy,

When in the level 3: User login, I am unable to complete the creation of a contract due to the entity field not having any selections available. However, when I am in the Level 1: Admin login, the entity selections are visible and available for me to choose. The picture provided below will give the correct pathway to the issue I am encountering. 
 
![Contract Crreation Error Level 3 User](https://github.com/BVCOG-Contract-Management/BVGOG-Contract-Manager/assets/148393555/cf2e4e7b-8111-4999-b024-b6942e2d5c4e)

This picture is of the level Admin login which has no issue.
![Contract Creation Level 1 Admin non issue](https://github.com/BVCOG-Contract-Management/BVGOG-Contract-Manager/assets/148393555/fc4f47e9-e8da-495e-87dd-402808e01c5d)

**Comment by lai-huy** [comment]
# Reason for Behavior
The reason is because the User is not part of the Entity.
Admin can see all entities and can create contracts for everyone.
Users can only see the Entities to which they are a member.

# Potential Solution
When inviting a user to join the platform, specify which Entity or Entities he or she belongs to.

**Comment by TManzini** [comment]
Reopening, so that @RichardGOV can verify and report behavior from Potential Solution

**Comment by RichardGOV** [comment]
Howdy, 

I understand that level Admin has the ability to view and create all entity contracts. The reference to Admin was to provide a baseline of what it looks like when the contract creation function is working as opposed to not working under level User. There is either a bug causing this issue, or I need someone to assign the User login an entity so that I may properly test out the contract creation function for that level. I hope this has cleared up any confusion to what the problem is. Please let me know if further explanation is necessary.
